import { importProvidersFrom } from '@angular/core';
import {
  Apple,
  ChevronRight,
  Clock,
  Disc3,
  Download,
  Facebook,
  Flame,
  Headphones,
  Heart,
  Home,
  ListMusic,
  Mic2,
  MonitorSpeaker,
  MoreHorizontal,
  Music2,
  Pause,
  Play,
  Plus,
  Radio,
  Repeat,
  Search,
  Settings,
  Shuffle,
  SkipBack,
  SkipForward,
  TrendingUp,
  Volume2,
  LucideAngularModule,
} from 'lucide-angular';

/**
 * Every Lucide icon used across the app, registered once at the application
 * root. Components reference them by kebab-case `name` (e.g. `name="skip-back"`).
 */
export const lucideIconsProvider = importProvidersFrom(
  LucideAngularModule.pick({
    Apple,
    ChevronRight,
    Clock,
    Disc3,
    Download,
    Facebook,
    Flame,
    Headphones,
    Heart,
    Home,
    ListMusic,
    Mic2,
    MonitorSpeaker,
    MoreHorizontal,
    Music2,
    Pause,
    Play,
    Plus,
    Radio,
    Repeat,
    Search,
    Settings,
    Shuffle,
    SkipBack,
    SkipForward,
    TrendingUp,
    Volume2,
  }),
);
